name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  Linux:
    runs-on: ubuntu-18.04
    container: cr.amira.io/gi0baro/pyoxidizer/musl:0.20.0

    steps:
      - uses: actions/checkout@v2
      - name: Get build version
        id: build_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Build release
        run: |
          make build_linux
          build/x86_64-unknown-linux-musl/release/install/noir --version
          make pack_linux BUILD_VERSION=${{ steps.build_version.outputs.version }}
          mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-musl.tar.gz dist/noir-${{ steps.build_version.outputs.version }}-linux-x86_64.tar.gz
          mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-musl.sha256sum dist/noir-${{ steps.build_version.outputs.version }}-linux-x86_64.sha256sum
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: noir-${{ steps.build_version.outputs.version }}-linux-x86_64.tar.gz
          path: dist/noir-${{ steps.build_version.outputs.version }}-linux-x86_64.tar.gz
      - name: Upload checksum file
        uses: actions/upload-artifact@v1
        with:
          name: noir-${{ steps.build_version.outputs.version }}-linux-x86_64.sha256sum
          path: dist/noir-${{ steps.build_version.outputs.version }}-linux-x86_64.sha256sum

  MacOS:
    runs-on: macos-11

    env:
      PYOXIDIZER_SYSTEM_RUST: "1"

    steps:
      - uses: actions/checkout@v2
      - name: Get build version
        id: build_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.56
          default: true
          profile: minimal
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install PyOxidizer
        run: |
          pip install pyoxidizer==0.20.0
      - name: Build release
        run: |
          make build_mac ARCH=x86_64-apple-darwin
          build/x86_64-apple-darwin/release/install/noir --version
          make pack_mac ARCH=x86_64-apple-darwin BUILD_VERSION=${{ steps.build_version.outputs.version }}
          mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz dist/noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.tar.gz
          mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum dist/noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.sha256sum
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.tar.gz
          path: dist/noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.tar.gz
      - name: Upload checksum file
        uses: actions/upload-artifact@v1
        with:
          name: noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.sha256sum
          path: dist/noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.sha256sum

  Windows:
    runs-on: windows-2019

    env:
      PYOXIDIZER_SYSTEM_RUST: "1"

    steps:
    - uses: actions/checkout@v2
    - name: Get build version
      id: build_version
      shell: bash
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/tags/}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.56
        default: true
        profile: minimal
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install PyOxidizer
      run: |
        pip install pyoxidizer==0.20.0
    - name: Build release
      run: |
        make build_win
        build/x86_64-pc-windows-msvc/release/install/noir --version
        make pack_win BUILD_VERSION=${{ steps.build_version.outputs.version }}
        mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.tar.gz dist/noir-${{ steps.build_version.outputs.version }}-windows-x86_64.tar.gz
        mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.sha256sum dist/noir-${{ steps.build_version.outputs.version }}-windows-x86_64.sha256sum
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: noir-${{ steps.build_version.outputs.version }}-windows-x86_64.tar.gz
        path: dist/noir-${{ steps.build_version.outputs.version }}-windows-x86_64.tar.gz
    - name: Upload checksum file
      uses: actions/upload-artifact@v1
      with:
        name: noir-${{ steps.build_version.outputs.version }}-windows-x86_64.sha256sum
        path: dist/noir-${{ steps.build_version.outputs.version }}-windows-x86_64.sha256sum

  Release:
    needs: [Linux, MacOS, Windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Download Linux release file
        uses: actions/download-artifact@master
        with:
          name: noir-${{ steps.tag.outputs.tag }}-linux-x86_64.tar.gz
          path: dist/
      - name: Download Linux checksum file
        uses: actions/download-artifact@master
        with:
          name: noir-${{ steps.tag.outputs.tag }}-linux-x86_64.sha256sum
          path: dist/
      - name: Download MacOS release file
        uses: actions/download-artifact@master
        with:
          name: noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.tar.gz
          path: dist/
      - name: Download MacOS checksum file
        uses: actions/download-artifact@master
        with:
          name: noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.sha256sum
          path: dist/
      - name: Download Windows release file
        uses: actions/download-artifact@master
        with:
          name: noir-${{ steps.tag.outputs.tag }}-windows-x86_64.tar.gz
          path: dist/
      - name: Download Windows checksum file
        uses: actions/download-artifact@master
        with:
          name: noir-${{ steps.tag.outputs.tag }}-windows-x86_64.sha256sum
          path: dist/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
      - name: Upload Linux release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-linux-x86_64.tar.gz
          asset_name: noir-${{ steps.tag.outputs.tag }}-linux-x86_64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Linux checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-linux-x86_64.sha256sum
          asset_name: noir-${{ steps.tag.outputs.tag }}-linux-x86_64.sha256sum
          asset_content_type: text/plain
      - name: Upload MacOS release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.tar.gz
          asset_name: noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.tar.gz
          asset_content_type: application/gzip
      - name: Upload MacOS checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.sha256sum
          asset_name: noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.sha256sum
          asset_content_type: text/plain
      - name: Upload Windows release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-windows-x86_64.tar.gz
          asset_name: noir-${{ steps.tag.outputs.tag }}-windows-x86_64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Windows checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-windows-x86_64.sha256sum
          asset_name: noir-${{ steps.tag.outputs.tag }}-windows-x86_64.sha256sum
          asset_content_type: text/plain
