name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  Linux-x86:
    runs-on: ubuntu-latest
    container: ghcr.io/gi0baro/pyoxidizer:0.24.0-musl

    steps:
      - uses: actions/checkout@v4
      - name: Get build version
        id: build_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Build release
        run: |
          make build_linux
          make pack_linux BUILD_VERSION=${{ steps.build_version.outputs.version }}
          mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-musl.tar.gz dist/noir-${{ steps.build_version.outputs.version }}-linux-x86_64.tar.gz
          mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-musl.sha256sum dist/noir-${{ steps.build_version.outputs.version }}-linux-x86_64.sha256sum
      - name: Upload release file
        uses: actions/upload-artifact@v3
        with:
          name: noir-${{ steps.build_version.outputs.version }}-linux-x86_64.tar.gz
          path: dist/noir-${{ steps.build_version.outputs.version }}-linux-x86_64.tar.gz
      - name: Upload checksum file
        uses: actions/upload-artifact@v3
        with:
          name: noir-${{ steps.build_version.outputs.version }}-linux-x86_64.sha256sum
          path: dist/noir-${{ steps.build_version.outputs.version }}-linux-x86_64.sha256sum

  # Linux-arm:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Get build version
  #     id: build_version
  #     run: |
  #       echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)
  #   - uses: uraimo/run-on-arch-action@v2
  #     name: Build release
  #     with:
  #       base_image: --platform=linux/arm64 ghcr.io/gi0baro/pyoxidizer:0.24.0-gnu
  #       env: |
  #         BUILD_VERSION: ${{ steps.build_version.outputs.version }}
  #       run: |
  #         make build_linux ARCH=aarch64-unknown-linux-gnu
  #         make pack_linux ARCH=aarch64-unknown-linux-gnu BUILD_VERSION=$BUILD_VERSION
  #         mv dist/noir-${{ steps.build_version.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz dist/noir-${{ steps.build_version.outputs.version }}-linux-aarch64.tar.gz
  #         mv dist/noir-${{ steps.build_version.outputs.version }}-aarch64-unknown-linux-gnu.sha256sum dist/noir-${{ steps.build_version.outputs.version }}-linux-aarch64.sha256sum
  #   - name: Upload release file
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: noir-${{ steps.build_version.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz
  #       path: dist/noir-${{ steps.build_version.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz
  #   - name: Upload checksum file
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: noir-${{ steps.build_version.outputs.version }}-aarch64-unknown-linux-gnu.sha256sum
  #       path: dist/noir-${{ steps.build_version.outputs.version }}-aarch64-unknown-linux-gnu.sha256sum

  MacOS-x86:
    runs-on: macos-12

    env:
      PYOXIDIZER_SYSTEM_RUST: "1"

    steps:
      - uses: actions/checkout@v4
      - name: Get build version
        id: build_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.66"
          default: true
          profile: minimal
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install PyOxidizer
        run: |
          pip install pyoxidizer==0.24.0
      - name: Build x86_64 release
        run: |
          make build_mac ARCH=x86_64-apple-darwin
          make pack_mac ARCH=x86_64-apple-darwin BUILD_VERSION=${{ steps.build_version.outputs.version }}
          mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz dist/noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.tar.gz
          mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum dist/noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.sha256sum
      - name: Upload release file
        uses: actions/upload-artifact@v3
        with:
          name: noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.tar.gz
          path: dist/noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.tar.gz
      - name: Upload checksum file
        uses: actions/upload-artifact@v3
        with:
          name: noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.sha256sum
          path: dist/noir-${{ steps.build_version.outputs.version }}-darwin-x86_64.sha256sum

  MacOS-arm:
    runs-on: macos-14

    env:
      PYOXIDIZER_SYSTEM_RUST: "1"

    steps:
      - uses: actions/checkout@v4
      - name: Get build version
        id: build_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.66"
          default: true
          profile: minimal
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install PyOxidizer
        run: |
          pip install pyoxidizer==0.24.0
      - name: Build aarch64 release
        run: |
          make build_mac ARCH=aarch64-apple-darwin
          make pack_mac ARCH=aarch64-apple-darwin BUILD_VERSION=${{ steps.build_version.outputs.version }}
          mv dist/noir-${{ steps.build_version.outputs.version }}-aarch64-apple-darwin.tar.gz dist/noir-${{ steps.build_version.outputs.version }}-darwin-aarch64.tar.gz
          mv dist/noir-${{ steps.build_version.outputs.version }}-aarch64-apple-darwin.sha256sum dist/noir-${{ steps.build_version.outputs.version }}-darwin-aarch64.sha256sum
      - name: Upload release file
        uses: actions/upload-artifact@v3
        with:
          name: noir-${{ steps.build_version.outputs.version }}-darwin-aarch64.tar.gz
          path: dist/noir-${{ steps.build_version.outputs.version }}-darwin-aarch64.tar.gz
      - name: Upload checksum file
        uses: actions/upload-artifact@v3
        with:
          name: noir-${{ steps.build_version.outputs.version }}-darwin-aarch64.sha256sum
          path: dist/noir-${{ steps.build_version.outputs.version }}-darwin-aarch64.sha256sum

  Windows:
    runs-on: windows-2019

    env:
      PYOXIDIZER_SYSTEM_RUST: "1"

    steps:
    - uses: actions/checkout@v4
    - name: Get build version
      id: build_version
      shell: bash
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/tags/}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.66"
        default: true
        profile: minimal
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install PyOxidizer
      run: |
        pip install pyoxidizer==0.24.0
    - name: Build release
      run: |
        make build_win
        make pack_win BUILD_VERSION=${{ steps.build_version.outputs.version }}
        mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.tar.gz dist/noir-${{ steps.build_version.outputs.version }}-windows-x86_64.tar.gz
        mv dist/noir-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.sha256sum dist/noir-${{ steps.build_version.outputs.version }}-windows-x86_64.sha256sum
    - name: Upload release file
      uses: actions/upload-artifact@v3
      with:
        name: noir-${{ steps.build_version.outputs.version }}-windows-x86_64.tar.gz
        path: dist/noir-${{ steps.build_version.outputs.version }}-windows-x86_64.tar.gz
    - name: Upload checksum file
      uses: actions/upload-artifact@v3
      with:
        name: noir-${{ steps.build_version.outputs.version }}-windows-x86_64.sha256sum
        path: dist/noir-${{ steps.build_version.outputs.version }}-windows-x86_64.sha256sum

  Release:
    needs: [Linux-x86, MacOS-x86, MacOS-arm, Windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Download Linux release file
        uses: actions/download-artifact@v3
        with:
          name: noir-${{ steps.tag.outputs.tag }}-linux-x86_64.tar.gz
          path: dist/
      - name: Download Linux checksum file
        uses: actions/download-artifact@v3
        with:
          name: noir-${{ steps.tag.outputs.tag }}-linux-x86_64.sha256sum
          path: dist/
      - name: Download MacOS x86_64 release file
        uses: actions/download-artifact@v3
        with:
          name: noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.tar.gz
          path: dist/
      - name: Download MacOS x86_64 checksum file
        uses: actions/download-artifact@v3
        with:
          name: noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.sha256sum
          path: dist/
      - name: Download MacOS aarch64 release file
        uses: actions/download-artifact@v3
        with:
          name: noir-${{ steps.tag.outputs.tag }}-darwin-aarch64.tar.gz
          path: dist/
      - name: Download MacOS aarch64 checksum file
        uses: actions/download-artifact@v3
        with:
          name: noir-${{ steps.tag.outputs.tag }}-darwin-aarch64.sha256sum
          path: dist/
      - name: Download Windows release file
        uses: actions/download-artifact@v3
        with:
          name: noir-${{ steps.tag.outputs.tag }}-windows-x86_64.tar.gz
          path: dist/
      - name: Download Windows checksum file
        uses: actions/download-artifact@v3
        with:
          name: noir-${{ steps.tag.outputs.tag }}-windows-x86_64.sha256sum
          path: dist/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
      - name: Upload Linux release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-linux-x86_64.tar.gz
          asset_name: noir-${{ steps.tag.outputs.tag }}-linux-x86_64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Linux checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-linux-x86_64.sha256sum
          asset_name: noir-${{ steps.tag.outputs.tag }}-linux-x86_64.sha256sum
          asset_content_type: text/plain
      - name: Upload MacOS x86_64 release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.tar.gz
          asset_name: noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.tar.gz
          asset_content_type: application/gzip
      - name: Upload MacOS x86_64 checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.sha256sum
          asset_name: noir-${{ steps.tag.outputs.tag }}-darwin-x86_64.sha256sum
          asset_content_type: text/plain
      - name: Upload MacOS aarch64 release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-darwin-aarch64.tar.gz
          asset_name: noir-${{ steps.tag.outputs.tag }}-darwin-aarch64.tar.gz
          asset_content_type: application/gzip
      - name: Upload MacOS aarch64 checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-darwin-aarch64.sha256sum
          asset_name: noir-${{ steps.tag.outputs.tag }}-darwin-aarch64.sha256sum
          asset_content_type: text/plain
      - name: Upload Windows release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-windows-x86_64.tar.gz
          asset_name: noir-${{ steps.tag.outputs.tag }}-windows-x86_64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Windows checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/noir-${{ steps.tag.outputs.tag }}-windows-x86_64.sha256sum
          asset_name: noir-${{ steps.tag.outputs.tag }}-windows-x86_64.sha256sum
          asset_content_type: text/plain
